In [13]:
import numpy as np
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,1],[9,8,7]])
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a/b)
print(a//b)
print(a%b)
print(a.max())
print(a.mean())
print(np.median(b))
b=b.transpose()

[[ 3  5  4]
 [11 11 11]]
[[-1 -1  2]
 [-7 -5 -3]]
[[ 2  6  3]
 [18 24 28]]
[[    1     8     3]
 [  512  6561 16384]]
[[0.5        0.66666667 3.        ]
 [0.22222222 0.375      0.57142857]]
[[0 0 3]
 [0 0 0]]
[[1 2 0]
 [2 3 4]]
4
2.5
5.0


In [14]:
np.dot(a,b)

array([[11, 46],
       [17, 70]])